{{ range .Values.sc }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .pvName }}
spec:
  capacity:
    storage: {{ .storage }}
  accessModes:
    {{ range .accessModes -}}
    - {{ . }}
    {{ end }}
  persistentVolumeReclaimPolicy: {{ .reclaimPolicy }}
  storageClassName: {{ .scName }}
  {{- if eq .provisioner "kubernetes.io/no-provisioner" }}
  volumeMode: Filesystem
  local:
    path: {{ .localStorage.path }}
    nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            {{- range .localStorage.nodeAffinity }}
            - key: {{ .selectorKey }}
              operator: In
              values:
                - {{ .selectorValues -}}
            {{ end }}
  {{- else if eq .provisioner "kubernetes.io/aws-ebs" }}
  awsElasticBlockStore:
    volumeID: {{ .awsStorage.volumeID }}
    fsType: {{ .parametersAws.fsType }}
  {{ else if eq .provisioner "kubernetes.io/rbd" }}
  {{ end }}
{{ end }}
